# languages: ["en", "ko"]
# exclude_from_localizations: ["javascript", "images", "css"]
title: 이윤석 - 독립 문화예술 창작가
description: 대한민국의 독립 문화예술 창작가 이윤석의 개인 누리집. 소개와 작품, 인생, 그리고 정보를 기록.
baseurl: ""
url: "https://Lee-Yunseok.github.io"
username: Lee Yunseok
user_description: Independent Cultural Artist
email: thericke00@gmail.com
facebook_username: ricke00
twitter_username: LYunseok
github_username:  lee-yunseok
gplus_username:  113958407890707437458
disqus_username: lee-yunseok
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate-v2
# - jekyll-multiple-languages-plugin
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
links:
  - title: <i class="fas fa-home"></i> Home
    url: /
  - title: <i class="fas fa-user-secret"></i> About
    url: /about
  - title: <i class="fas fa-id-card"></i> Works
    url: /works
  - title: <i class="fas fa-archive"></i> Life
    url: /life
  - title: <i class="fas fa-briefcase"></i> Info
    url: /info
  - title: <i class="fas fa-tag"></i> Tags
    url: /tags
jekyll-archives:
  enabled: all
  layout: archive
permalinks:
  year: '/archives/year/:year/'
  month: '/archives/month/:year-:month/'
  day: '/archives/:year/:month/:day/'
  tag: '/archives/tag/:name/'
  category: '/archives/category/:name/'
pagination:
    enabled: true
    debug: false
    collection: 'posts'
    per_page: 10
    permalink: '/page/:num/'
    title: ':title - page :num'
    limit: 0
    sort_field: 'date'
    sort_reverse: true
    category: 'posts'
    tag: ''
    locale: '' 
    trail: 
        before: 2
        after: 2
    extension: html
    indexpage: 'index'
defaults:
    scope:
      path: "_slides" 
    values:
      layout: "iframe"
collections:
  slides:
    output: true
social:
    name: Lee Yunseok
    links:
        - https://twitter.com/LYunseok
        - https://www.facebook.com/ricke00
        - https://www.linkedin.com/in/leeyunseok/
        - https://plus.google.com/113958407890707437458
        - https://github.com/lee-yunseok
        - https://www.reddit.com/user/arisae86
        - https://steamcommunity.com/id/ricke00
webmaster_verifications:
  google: LCL5N4f_rHmixraltefHZ44HPIEJ-pJYwK4SmsoWrio
  bing: 9D74C20986AA90FC420EED9DCC027B55
exclude: ['package.json', 'src', 'node_modules']
